name: Looker Studio Scraper Suite

on:
  workflow_dispatch: {}
  schedule:
    # 08:05, 11:05, 14:05, 17:05, 20:05 London (UTC in cron)
    - cron: "5 7,10,13,16,19 * * *"

concurrency:
  group: looker-scrape
  cancel-in-progress: false

jobs:
  scrape:
    runs-on: ubuntu-latest
    timeout-minutes: 40

    steps:
      # ────────────────────────────────
      # Checkout
      # ────────────────────────────────
      - name: Checkout
        uses: actions/checkout@v4

      # ────────────────────────────────
      # System deps for OCR (pytesseract)
      # ────────────────────────────────
      - name: Install system packages (tesseract)
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends tesseract-ocr

      # ────────────────────────────────
      # Python + Playwright
      # ────────────────────────────────
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Python deps
        run: |
          python -m pip install -U pip
          pip install playwright requests pillow pytesseract
          python -m playwright install --with-deps chromium

      # ────────────────────────────────
      # Environment (date-based caching)
      # ────────────────────────────────
      - name: Export TODAY
        run: echo "TODAY=$(date -u +%Y%m%d)" >> $GITHUB_ENV

      # Optional: let scraper know where your ROI JSON is
      - name: Export ROI map path
        run: echo "ROI_MAP_FILE=${{ github.workspace }}/roi_map.json" >> $GITHUB_ENV

      # ────────────────────────────────
      # Restore state from cache
      # ────────────────────────────────
      - name: Restore scraper state (auth + logs + roi_map)
        id: cache-restore
        uses: actions/cache/restore@v4
        with:
          path: |
            auth_state.json
            comments_log.csv
            complaints_log.csv
            daily_report_log.csv
            roi_map.json
          key: scraper-state-${{ runner.os }}-v1-${{ github.ref_name }}-${{ env.TODAY }}
          restore-keys: |
            scraper-state-${{ runner.os }}-v1-${{ github.ref_name }}-
            scraper-state-${{ runner.os }}-v1-

      # ────────────────────────────────
      # Optional fallback (first cold start)
      # ────────────────────────────────
      - name: Fallback restore auth_state.json from secret
        run: |
          if [ -n "${AUTH_STATE_B64}" ]; then
            echo "${AUTH_STATE_B64}" | base64 --decode > auth_state.json
            echo "Decoded auth_state.json from AUTH_STATE_B64."
          else
            echo "No AUTH_STATE_B64 secret provided — continuing without."
          fi
        env:
          AUTH_STATE_B64: ${{ secrets.AUTH_STATE_B64 }}

      # ────────────────────────────────
      # Create config.ini dynamically from secrets
      # ────────────────────────────────
      - name: Create/Update config.ini from secrets
        run: |
          {
            echo "[DEFAULT]"
            echo "GOOGLE_EMAIL=${{ secrets.GOOGLE_EMAIL }}"
            echo "GOOGLE_PASSWORD=${{ secrets.GOOGLE_PASSWORD }}"
            echo "MAIN_WEBHOOK=${{ secrets.MAIN_WEBHOOK }}"
            echo "ALERT_WEBHOOK=${{ secrets.ALERT_WEBHOOK }}"
            echo "COMPLAINTS_WEBHOOK=${{ secrets.COMPLAINTS_WEBHOOK }}"
            echo "DAILY_WEBHOOK=${{ secrets.DAILY_WEBHOOK }}"
          } > config.ini

      # ────────────────────────────────
      # Run scrapers
      # ────────────────────────────────
      - name: Run NPS scraper
        run: xvfb-run -a python scrape.py now || true

      - name: Run Complaints scraper
        run: xvfb-run -a python scrape_complaints.py now || true

      - name: Run Daily Report scraper (OCR + ROI)
        env:
          ROI_MAP_FILE: ${{ env.ROI_MAP_FILE }}
        run: xvfb-run -a python scrape_daily.py || true

      # ────────────────────────────────
      # Show file states for debugging
      # ────────────────────────────────
      - name: Show state files
        run: |
          echo "::group::State files"
          for f in auth_state.json comments_log.csv complaints_log.csv daily_report_log.csv roi_map.json scrape.log scrape_complaints.log scrape_daily.log; do
            if [ -f "$f" ]; then
              echo "[OK] $f -> $(wc -c < "$f") bytes"
            else
              echo "[MISS] $f"
            fi
          done
          echo "::endgroup::"

          echo "::group::daily_report_log.csv (last 5)"
          if [ -f daily_report_log.csv ]; then tail -n 5 daily_report_log.csv || true; else echo "daily_report_log.csv not found"; fi
          echo "::endgroup::"

          echo "::group::screens/ listing"
          ls -lah screens || echo "no screens/"
          echo "::endgroup::"

      # ────────────────────────────────
      # Upload artifacts (includes ROI crops & overlay)
      # ────────────────────────────────
      - name: Upload logs, ROI, and screenshots
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: scraper-state-${{ github.run_id }}
          path: |
            auth_state.json
            comments_log.csv
            complaints_log.csv
            daily_report_log.csv
            roi_map.json
            scrape.log
            scrape_complaints.log
            scrape_daily.log
            screens/
          if-no-files-found: ignore

      # ────────────────────────────────
      # Save updated cache snapshot
      # ────────────────────────────────
      - name: Save updated scraper state to cache
        uses: actions/cache/save@v4
        with:
          path: |
            auth_state.json
            comments_log.csv
            complaints_log.csv
            daily_report_log.csv
            roi_map.json
          key: scraper-state-${{ runner.os }}-v1-${{ github.run_id }}
