name: 🧪 Test Daily Report Scraper

on:
  workflow_dispatch: {}  # Manual trigger only

concurrency:
  group: looker-scrape-test
  cancel-in-progress: true

jobs:
  test-daily:
    runs-on: ubuntu-latest
    timeout-minutes: 40

    steps:
      # ────────────────────────────────
      # Checkout
      # ────────────────────────────────
      - name: Checkout
        uses: actions/checkout@v4

      # ────────────────────────────────
      # System deps (OCR)
      # ────────────────────────────────
      - name: Install Tesseract OCR
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends tesseract-ocr
      # ────────────────────────────────
      # Python + Playwright
      # ────────────────────────────────
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Python deps
        run: |
          python -m pip install -U pip
          pip install playwright requests pillow pytesseract schedule pytz
          python -m playwright install --with-deps chromium
      # ────────────────────────────────
      # Env vars
      # ────────────────────────────────
      - name: Export TODAY, CI_RUN_URL, ROI_MAP_FILE
        run: |
          echo "TODAY=$(date -u +%Y%m%d)" >> $GITHUB_ENV
          echo "CI_RUN_URL=${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}" >> $GITHUB_ENV
          echo "ROI_MAP_FILE=${{ github.workspace }}/roi_map.json" >> $GITHUB_ENV
      # ────────────────────────────────
      # Restore scraper state (auth + CSV + ROI)
      # ────────────────────────────────
      - name: Restore scraper state (auth + logs + ROI)
        id: cache-restore
        uses: actions/cache/restore@v4
        with:
          path: |
            auth_state.json
            comments_log.csv
            complaints_log.csv
            daily_report_log.csv
            roi_map.json
          key: scraper-state-${{ runner.os }}-v1-${{ github.ref_name }}-${{ env.TODAY }}
          restore-keys: |
            scraper-state-${{ runner.os }}-v1-${{ github.ref_name }}-
            scraper-state-${{ runner.os }}-v1-
      # ────────────────────────────────
      # Fallback: decode auth_state.json from secret
      # ────────────────────────────────
      - name: Fallback restore auth_state.json from secret
        run: |
          if [ -n "${AUTH_STATE_B64}" ]; then
            echo "${AUTH_STATE_B64}" | base64 --decode > auth_state.json
            echo "Decoded auth_state.json from AUTH_STATE_B64."
          else
            echo "No AUTH_STATE_B64 secret provided — continuing without."
          fi
        env:
          AUTH_STATE_B64: ${{ secrets.AUTH_STATE_B64 }}

      # ────────────────────────────────
      # Create config.ini (same as prod)
      # ────────────────────────────────
      - name: Create/Update config.ini
        run: |
          {
            echo "[DEFAULT]"
            echo "GOOGLE_EMAIL=${{ secrets.GOOGLE_EMAIL }}"
            echo "GOOGLE_PASSWORD=${{ secrets.GOOGLE_PASSWORD }}"
            echo "MAIN_WEBHOOK=${{ secrets.MAIN_WEBHOOK }}"
            echo "ALERT_WEBHOOK=${{ secrets.ALERT_WEBHOOK }}"
            echo "COMPLAINTS_WEBHOOK=${{ secrets.COMPLAINTS_WEBHOOK }}"
            echo "DAILY_WEBHOOK=${{ secrets.DAILY_TEST_WEBHOOK || secrets.DAILY_WEBHOOK }}"
          } > config.ini
      
      # ────────────────────────────────
      # Run only Daily Report scraper
      # ────────────────────────────────
      - name: Remove cached/old roi_map.json to use script default
        run: |
          if [ -f ${{ env.ROI_MAP_FILE }} ]; then
            echo "Deleting cached/old roi_map.json to force script's embedded DEFAULT_ROI_MAP."
            rm ${{ env.ROI_MAP_FILE }}
          fi

      - name: Run Daily Report Scraper (OCR + ROI)
        env:
          CI_RUN_URL: ${{ env.CI_RUN_URL }}
          ROI_MAP_FILE: ${{ env.ROI_MAP_FILE }}
        run: xvfb-run -a python scrape_daily.py || true

      # ────────────────────────────────
      # Show summary info
      # ────────────────────────────────
      - name: Show summary + debug
        run: |
          echo "::group::State files"
          for f in auth_state.json daily_report_log.csv roi_map.json scrape_daily.log; do
            if [ -f "$f" ]; then
              echo "[OK] $f → $(wc -c < "$f") bytes"
            else
              echo "[MISS] $f"
            fi
          done
          echo "::endgroup::"
          echo "::group::Last 5 log lines"
          tail -n 5 scrape_daily.log || true
          echo "::endgroup::"
      # ────────────────────────────────
      # Upload artifacts
      # ────────────────────────────────
      - name: Upload logs and screenshots
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-daily-report-${{ github.run_id }}
          path: |
            auth_state.json
            daily_report_log.csv
            roi_map.json
            scrape_daily.log
            screens/
          if-no-files-found: ignore

      # ────────────────────────────────
      # Save updated state to cache
      # ────────────────────────────────
      - name: Save updated cache
        uses: actions/cache/save@v4
        with:
          path: |
            auth_state.json
            daily_report_log.csv
            roi_map.json
          key: scraper-state-${{ runner.os }}-v1-${{ github.run_id }}
